MODEL:
  TYPE: rep_vit_m1_dyt
  # PRETRAINED: output/rep_vit_m1_dyt_fuse_sa_distill/default/ckpt_epoch_19.pth
  PRETRAINED: output/rep_vit_m1_dyt_fuse_enc_dec_4m_ft_bp_iter2b_sa_distill/default/ckpt_epoch_39.pth
  MASK_HQ: True

TRAIN:
  EPOCHS: 48
  BASE_LR: 3.2e-4
  MIN_LR: 3.2e-5
  WARMUP_LR: 3.2e-6
  WARMUP_EPOCHS: 8
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 0.01
  EVAL_BN_WHEN_TRAINING: True
  ENABLE_DISTILL: True

DATA:
  IMG_SIZE: 1024
  MEAN_AND_STD_TYPE: default
  NUM_WORKERS: 16
  BATCH_SIZE: 8

DISTILL:
  ENCODER_ONLY: False
  EMBED_DIM: 256
  NO_RAND: True
  FUSE: True
  FREEZE_IMAGE_ENCODER: True
  FREEZE_PROMPT_ENCODER: True
  FREEZE_MASK_DECODER: True
  GELU_APPROX: tanh
  MASK_DYT: True
  DECODER_BCE: 1.0
  DECODER_DICE: 1.0
  USE_TEACHER_LOGITS: True
  TEMPERATURE: 4.0
  # MAX_ALLOWED_PROMPTS: 16
  PROMPT_TYPE: ['box', 'point']
  DECODE_ITERS: 2
  POINTS_PER_REFINE_ITER: 1
  ITER_ON_BOX: True

AMP_ENABLE: False